site_name: SERPS Documentation

site_url: http://serp-spider.github.io/documentation

pages:
  - Documentation:
    - About SERPS: index.md
    - Overview: overview.md
    - Cookies: cookies.md

  - Search Engines:
    - Google: search-engine/google.md

  - Http Clients:
      - CURL: http-client/curl.md
      - PhantomJS: http-client/phantomJS.md

  - About:
    - Packages: about/packages.md

  - _hidden:
    - Parse a Page: search-engine/google/parse-page.md

repo_url: https://github.com/serp-spider

theme_dir: 'themes/serps'

site_description: >
  SERPS is a SERP Scraper for php.
  It offers a set of tools to manipulate and parse popular search engines such as Google, Yahoo, Bing...

site_favicon: favicon.ico

google_analytics:
  - UA-75620778-1
  - serp-spider.github.io


markdown_extensions:
  - admonition